### ISSUE TITLE
PC サイズでの各プロダクトレイアウト統一したい

### ISSUE THREAD

**Issue by drcm-ogawa-mitsunori** [drip-pages/drip-official-dev#44]
<img width="380" alt="スクリーンショット 2019-09-02 12 11 25" src="https://user-images.githubusercontent.com/11750757/64088109-e39e0900-cd7a-11e9-9ab3-b281fc508b66.png">

- 左サムネと右ロゴの top を合わせる
- 右側のロゴ、説明文、URL のマージンを合わせる

**Comment by fukui-takanori** [comment]
全体として既存ページに合わせました。

* 左サムネと右ロゴのtopを合わせました。
  * LoveChainのみ、横に長いサムネのため、画面サイズによってはTOPが揃いません。
  （既存ページでも同様）
* 右側のロゴ、説明文、URLのマージンを合わせる
  * 既存ページに合わせて調整しています。
  * 各ロゴのサイズが統一されていないため、各Inventionごとに画像サイズとマージンを調整しています。

**Comment by drcm-ogawa-mitsunori** [comment]
### now

<img width="257" alt="スクリーンショット 2019-09-03 11 43 06" src="https://user-images.githubusercontent.com/11750757/64140958-4ce84f80-ce41-11e9-97fb-339c51d93624.png">

右側**だけ**で見ると良くなったが、全体としてギクシャクしているので、元デザインに寄せたいです。

### feature

<img width="252" alt="スクリーンショット 2019-09-03 11 43 18" src="https://user-images.githubusercontent.com/11750757/64140974-625d7980-ce41-11e9-978e-e8e598ac2e44.png">

アイコン右側とテキスト左側で位置統一されてる感じ？

**Comment by fukui-takanori** [comment]
![スクリーンショット 2019-09-03 15 45 43](https://user-images.githubusercontent.com/52432522/64149829-fa6b5b00-ce61-11e9-9dda-0e3ed959c38d.png)
