### ISSUE TITLE
`/en` ページが存在しない

### ISSUE THREAD

**Issue by drcm-ogawa-mitsunori** [drip-pages/drip-official-dev#55]
https://drip-pages.github.io/drip-official-dev/en

現行サイトは

- https://drip.drecom.co.jp/
- https://drip.drecom.co.jp/en
- https://drip.drecom.co.jp/news

の3ページなので、それに合わせたい。

**Comment by fukui-takanori** [comment]
`/en`ページを存在させるようにした。
しかし、コードがスパゲティのため、Redux導入後、清掃する
https://github.com/drip-pages/drip-official-dev/issues/56
